User can view their entry
moamel97/code-journal pull request #6
Opened 2021-10-29 03:27 UTC by moamel97

![Kapture 2021-10-28 at 20 25 40](https://user-images.githubusercontent.com/90476994/139370741-fa681ffc-a33f-4342-b264-bb18773a2c0e.gif)

2021-10-31 00:03 UTC, moamel97 commented
![Kapture 2021-10-30 at 16 59 01](https://user-images.githubusercontent.com/90476994/139561567-a95dcae3-a5b0-4441-a548-a60a6e04c6ca.gif)

2021-11-01 16:58 UTC, codingcodymiller requested changes

2021-11-01 16:58 UTC, codingcodymiller commented on css/styles.css
> +} */
Please remove commented code prior to submitting for review

2021-11-01 16:58 UTC, codingcodymiller commented on css/styles.css
> +  left: 20rem;
This is a _**huge**_ value. Why is this necessary?

2021-11-01 16:58 UTC, codingcodymiller commented on js/main.js
> +    hideNoEntry();
What is the purpose of these lines?

2021-11-01 16:58 UTC, codingcodymiller commented on js/main.js
> +  if (viewEntry === false) {
What is this conditional for?

2021-11-01 16:58 UTC, codingcodymiller commented on js/main.js
> +  event.preventDefault();
This isn't a `submit` event handler, this line shouldn't be necessary

2021-11-04 23:34 UTC, moamel97 commented
![Kapture 2021-11-04 at 16 32 10](https://user-images.githubusercontent.com/90476994/140434470-7ddce632-484f-4bad-b1eb-f118bb5e85b7.gif)

2021-11-04 23:36 UTC, codingcodymiller approved these changes

2021-11-04 23:39 UTC, merged